services:
  backend:
    build: ./backend
    env_file:
      - .env
    volumes:
      - ./db.sqlite3:/app/db.sqlite3
      - ./weights:/app/weights

  frontend:
    build: ./frontend
    ports:
      - "80:80"
